# Generated by Django 2.2.1 on 2019-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('note', models.TextField(max_length=400, null=True, verbose_name='メモ')),
                ('date', models.DateField(verbose_name='日付')),
            ],
        ),
    ]
