# Generated by Django 2.2.1 on 2019-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20190506_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='画像'),
        ),
    ]
